-- Generated from generator/demo_specs/aws-indonesia-mining-nickel-supply-chain.json
-- Regenerate with: python3 generator/gen_repo_docs.py aws-indonesia-mining-nickel-supply-chain
-- This is the schema that is actually deployed for ID_MINING_NICKEL_SUPPLY_CHAIN.

-- Alerts fire on the bottom tail of Port Queue
-- (lower is worse for this metric).
CREATE OR REPLACE DYNAMIC TABLE CURATED.PERFORMANCE_SUMMARY
  TARGET_LAG = '30 days' WAREHOUSE = TOURISM_WH
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS
WITH thresh AS (
  SELECT PERCENTILE_CONT(0.09) WITHIN GROUP (ORDER BY KPI_PORT_QUEUE) AS T
  FROM RAW.PRODUCTION_LOGS
)
SELECT
  e.ID AS ENTITY_ID,
  e.NAME AS ENTITY_NAME,
  e.REGION,
  e.CATEGORY,
  e.STATUS,
  COUNT(*) AS EVENT_COUNT,
  SUM(CASE WHEN f.KPI_PORT_QUEUE <= (SELECT T FROM thresh) THEN 1 ELSE 0 END) AS ALERT_COUNT,
  ROUND(AVG(f.KPI_PORT_QUEUE), 2) AS AVG_PORT_QUEUE,
  ROUND(AVG(f.KPI_HAULING_COST_WMT), 2) AS AVG_HAULING_COST_WMT,
  ROUND(AVG(f.KPI_PORT_UTILIZATION), 2) AS AVG_PORT_UTILIZATION,
  ROUND(AVG(f.KPI_VESSEL_TURNAROUND), 2) AS AVG_VESSEL_TURNAROUND
FROM RAW.PRODUCTION_LOGS f
JOIN RAW.PROCESSING_PLANTS e ON e.ID = f.ENTITY_ID
CROSS JOIN thresh
GROUP BY e.ID, e.NAME, e.REGION, e.CATEGORY, e.STATUS;

CREATE OR REPLACE DYNAMIC TABLE CURATED.TREND_ANALYSIS
  TARGET_LAG = '30 days' WAREHOUSE = TOURISM_WH
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS
SELECT
  f.EVENT_DATE AS METRIC_DATE,
  COUNT(*) AS EVENT_COUNT,
  ROUND(AVG(f.KPI_PORT_QUEUE), 2) AS AVG_PORT_QUEUE,
  ROUND(AVG(f.KPI_HAULING_COST_WMT), 2) AS AVG_HAULING_COST_WMT,
  ROUND(AVG(f.KPI_PORT_UTILIZATION), 2) AS AVG_PORT_UTILIZATION,
  ROUND(AVG(f.KPI_VESSEL_TURNAROUND), 2) AS AVG_VESSEL_TURNAROUND
FROM RAW.PRODUCTION_LOGS f
GROUP BY f.EVENT_DATE;

-- DISPLAY is rendered here so it is byte-identical to the card the app
-- was designed with (asserted by the round-trip check in kpi_parse.py).
CREATE OR REPLACE DYNAMIC TABLE CURATED.KPI_SUMMARY
  TARGET_LAG = '30 days' WAREHOUSE = TOURISM_WH
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS WITH ev AS (SELECT AVG(KPI_PORT_QUEUE) AS KPI_PORT_QUEUE, AVG(KPI_HAULING_COST_WMT) AS KPI_HAULING_COST_WMT, AVG(KPI_PORT_UTILIZATION) AS KPI_PORT_UTILIZATION, AVG(KPI_VESSEL_TURNAROUND) AS KPI_VESSEL_TURNAROUND FROM RAW.PRODUCTION_LOGS),
     en AS (SELECT SUM(KPI_SHIPMENTS_MTD) AS KPI_SHIPMENTS_MTD, SUM(KPI_ORE_STOCKPILE) AS KPI_ORE_STOCKPILE, SUM(KPI_ACTIVE_HAULERS) AS KPI_ACTIVE_HAULERS FROM RAW.PROCESSING_PLANTS)
  SELECT 1 AS SORT_ORDER, 'Shipments (MTD)' AS TITLE, KPI_SHIPMENTS_MTD AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_SHIPMENTS_MTD)) AS DECIMAL(38,0))) || ' ' || 'vessels' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 2 AS SORT_ORDER, 'Port Queue' AS TITLE, KPI_PORT_QUEUE AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_PORT_QUEUE)) AS DECIMAL(38,0))) || ' ' || 'days' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 3 AS SORT_ORDER, 'Ore Stockpile' AS TITLE, KPI_ORE_STOCKPILE AS VALUE_NUM, TO_VARCHAR(CAST(ROUND(((KPI_ORE_STOCKPILE) / 1000000), 1) AS DECIMAL(38,1))) || 'M' || ' ' || 'WMT' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 4 AS SORT_ORDER, 'Active Haulers' AS TITLE, KPI_ACTIVE_HAULERS AS VALUE_NUM, LTRIM(TO_VARCHAR(CAST(ROUND((KPI_ACTIVE_HAULERS)) AS DECIMAL(38,0)), '999,999,999,999')) AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 5 AS SORT_ORDER, 'Hauling Cost/WMT' AS TITLE, KPI_HAULING_COST_WMT AS VALUE_NUM, 'Rp' || ' ' || TO_VARCHAR(CAST(ROUND(((KPI_HAULING_COST_WMT) / 1000)) AS DECIMAL(38,0))) || 'K' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 6 AS SORT_ORDER, 'Port Utilization' AS TITLE, KPI_PORT_UTILIZATION AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_PORT_UTILIZATION)) AS DECIMAL(38,0))) || '%' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 7 AS SORT_ORDER, 'Vessel Turnaround' AS TITLE, KPI_VESSEL_TURNAROUND AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_VESSEL_TURNAROUND), 1) AS DECIMAL(38,1))) || ' ' || 'days' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en;

ALTER DYNAMIC TABLE CURATED.PERFORMANCE_SUMMARY SUSPEND;
ALTER DYNAMIC TABLE CURATED.TREND_ANALYSIS SUSPEND;
ALTER DYNAMIC TABLE CURATED.KPI_SUMMARY SUSPEND;
