-- ============================================================================
-- 06_ML_MODELS.SQL — ML Functions for Nickel Supply Chain Visibility
-- ============================================================================
USE DATABASE NICKEL_SUPPLY_CHAIN;
USE SCHEMA ML;

-- ML.FORECAST: PRODUCTION_OUTPUT_FORECAST
CREATE OR REPLACE SNOWFLAKE.ML.FORECAST ML.PRODUCTION_OUTPUT_FORECAST(
  INPUT_DATA => SYSTEM$REFERENCE('TABLE', 'CURATED.PLANT_PERFORMANCE'),
  SERIES_COLNAME => 'PLANT_ID',
  TIMESTAMP_COLNAME => 'DS',
  TARGET_COLNAME => 'Y'
  
);

CREATE OR REPLACE TABLE ML.PRODUCTION_OUTPUT_FORECAST_RESULTS AS
SELECT * FROM TABLE(ML.PRODUCTION_OUTPUT_FORECAST!FORECAST(FORECASTING_PERIODS => 14));

-- ML.ANOMALY_DETECTION: GRADE_VARIANCE_MODEL
CREATE OR REPLACE SNOWFLAKE.ML.ANOMALY_DETECTION ML.GRADE_VARIANCE_MODEL(
  INPUT_DATA => SYSTEM$REFERENCE('TABLE', 'CURATED.GRADE_ANALYTICS'),
  SERIES_COLNAME => 'MINE_ID',
  TIMESTAMP_COLNAME => 'DS',
  TARGET_COLNAME => 'Y',
  LABEL_COLNAME => ''
);

CREATE OR REPLACE TABLE ML.GRADE_VARIANCE_MODEL_RESULTS AS
SELECT * FROM TABLE(ML.GRADE_VARIANCE_MODEL!DETECT_ANOMALIES(INPUT_DATA => SYSTEM$REFERENCE('TABLE', 'CURATED.GRADE_ANALYTICS'), SERIES_COLNAME => 'MINE_ID', TIMESTAMP_COLNAME => 'DS', TARGET_COLNAME => 'Y'));

