-- ============================================================================
-- 99_RESET.SQL — Reset Nickel Supply Chain Visibility to clean demo state
-- ============================================================================
USE DATABASE NICKEL_SUPPLY_CHAIN;

-- Suspend tasks during demo
ALTER TASK IF EXISTS APP.TASK_INGEST_PRODUCTION SUSPEND;
ALTER TASK IF EXISTS APP.TASK_FORECAST_OUTPUT SUSPEND;
ALTER TASK IF EXISTS APP.TASK_REFRESH_ICEBERG SUSPEND;

-- Force refresh Dynamic Tables
ALTER DYNAMIC TABLE CURATED.MATERIAL_BALANCE REFRESH;
ALTER DYNAMIC TABLE CURATED.PLANT_PERFORMANCE REFRESH;
ALTER DYNAMIC TABLE CURATED.DELIVERY_COMPLIANCE REFRESH;
ALTER DYNAMIC TABLE CURATED.GRADE_ANALYTICS REFRESH;

-- Verify key demo numbers
-- SELECT COUNT(*) FROM NICKEL_SUPPLY_CHAIN.RAW.MINES → 40
-- SELECT COUNT(*) FROM NICKEL_SUPPLY_CHAIN.RAW.MATERIAL_FLOW → 80000
-- SELECT COUNT(*) FROM NICKEL_SUPPLY_CHAIN.RAW.PRODUCTION_LOGS → 150000

-- Resume tasks
ALTER TASK IF EXISTS APP.TASK_REFRESH_ICEBERG RESUME;
ALTER TASK IF EXISTS APP.TASK_FORECAST_OUTPUT RESUME;
ALTER TASK IF EXISTS APP.TASK_INGEST_PRODUCTION RESUME;
